controller:
  config:
    use-proxy-protocol: "true"
    use-forwarded-headers: "true"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      service.beta.kubernetes.io/do-loadbalancer-hostname: "status.murmurations.network"
    externalTrafficPolicy: "Cluster"