apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ipfs.ic3.dev
    - ipfs-api.ic3.dev
    secretName: ic3-tls
  rules:
    - host: ipfs.ic3.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ipfs-ipfs-ipfs-cluster
                port:
                  number: 8080
    - host: ipfs-api.ic3.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ipfs-ipfs-ipfs-cluster
                port:
                  number: 5001
