apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - ipfs.ic3.dev
      secretName: ic3-ipfs-tls
  rules:
    - host: ipfs.ic3.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipfs-ipfs
                port:
                  number: 8080
